// Hand-written rather than generated by `wrangler types`. app-alpha and
// app-bravo declare the identical global `Env` shape; separate tsconfig
// projects keep the two declarations from colliding.
import type { LimiterService } from '../../../dist/do.js';

import type { StatusDO } from './index.js';

declare global {
  interface Env {
    /** The shared limiter Worker's named RPC entrypoint. */
    LIMITER: LimiterService;
    /**
     * HTTP hop to the upstream Worker. A plain fetch() of another Worker's
     * workers.dev URL is blocked (Cloudflare error 1042), so requests are
     * dispatched over this binding.
     */
    UPSTREAM: Fetcher;
    /** The mock upstream API's origin, used to build the request URL. */
    UPSTREAM_URL: string;
    /** This app's own request-state tracker: one instance, records every request. */
    STATUS: DurableObjectNamespace<StatusDO>;
  }
}

export {};
