// Hand-written rather than generated by `wrangler types`, so the demo has no
// build step beyond `npm run build` at the repo root. Every Worker in the demo
// declares its own global `Env` in its own tsconfig project, so these
// declarations never merge into one blob — each Worker's env stays honest.
import type { LimiterDO } from '../../../dist/do.js';

declare global {
  interface Env {
    RATE_LIMITER: DurableObjectNamespace<LimiterDO>;
    /** The shared secret guarding /configure and /stats. Unset denies everything. */
    DRL_CONFIG_KEY?: string;
  }
}

export {};
