// Hand-written rather than generated by `wrangler types`. The dashboard's own
// tsconfig project keeps this global `Env` from merging with any other Worker's.
declare global {
  interface Env {
    /**
     * The four DEPLOYED Workers, reached over service bindings with
     * "remote": true so `wrangler dev` connects to the real deployments. A plain
     * fetch() of another Worker's workers.dev URL is blocked (error 1042); the
     * binding is the supported path, and the fetch hostname is a dummy.
     */
    LIMITER_SVC: Fetcher;
    UPSTREAM_SVC: Fetcher;
    ALPHA_SVC: Fetcher;
    BRAVO_SVC: Fetcher;
    /**
     * The limiter's shared secret. A secret, never a var: used only server-side
     * so it never reaches the browser. Set it in `.dev.vars` for local dev —
     * secrets do not come down from Cloudflare. Unset means the limiter's /stats
     * and /configure return 401, which the dashboard surfaces inline.
     */
    DRL_CONFIG_KEY?: string;
  }
}

export {};
