// Hand-written rather than generated by `wrangler types`, so the harness has
// no build step beyond `npm run build` at the repo root.
import type { LimiterDO } from '../../../dist/do.js';

declare global {
  interface Env {
    RATE_LIMITER: DurableObjectNamespace<LimiterDO>;
  }
}

export {};
