// Hand-written rather than generated by `wrangler types`. This Worker's global
// `Env` is declared in its own tsconfig project, so it never merges with the
// apps' or the limiter's.
import type { MockApiDO } from './index.js';

declare global {
  interface Env {
    /** The single mock-API Durable Object: rolling window + counters. */
    MOCK: DurableObjectNamespace<MockApiDO>;
  }
}

export {};
