// Hand-written rather than generated by `wrangler types`, so the harness has
// no build step beyond `npm run build` at the repo root.
//
// `Env` is declared globally on purpose: `defineBinder` checks its argument
// against the Durable Object bindings of the global `Env`, by merging with an
// empty declaration of its own. That check is part of what is being verified,
// so `defineBinder('RATE_LIMITER')` in limiter-client.ts must resolve against
// this — misspell it there and the harness should fail to compile.
import type { LimiterDO, LimiterService } from '../../../dist/do.js';

import type { ProbeCollectorDO } from './collector.js';
import type { LimiterProbeParams } from './probe-workflow.js';

declare global {
  interface Env {
    /** Shared secret: wrangler secret put PROBE_KEY */
    PROBE_KEY: string;
    /** The default topology: the limiter Worker's named RPC entrypoint. */
    LIMITER: LimiterService;
    /** The escape hatch: the same object, bound cross-script in one hop. */
    RATE_LIMITER: DurableObjectNamespace<LimiterDO>;
    COLLECTOR: DurableObjectNamespace<ProbeCollectorDO>;
    PROBE: Workflow<LimiterProbeParams>;
  }
}

export {};
